### PR TITLE
add support for noble-curves

### PR DESCRIPTION
**Pull request by paulmillr**
https://github.com/paulmillr/noble-curves

### CODE REVIEW

**Comment by paulmillr** [comment]
@guidovranken ping

**Comment by paulmillr** [comment]
@guidovranken we need this

**Comment by guidovranken** [comment]
Thanks. How can we create a `noble-curves.js` that doesn't have any `require` statements? Basically we need to pack all JS code into 1 file.

**Comment by paulmillr** [comment]
modules/noble-curves have proper rollup config in place that allows to build file

**Comment by paulmillr** [comment]
@guidovranken fixed

**Comment by guidovranken** [comment]
Thank you. How shall we deal with this?

```
$ ./cryptofuzz --force-module=noble-curves ./crash-0001f73e5e9ceabae6cf7d3d0483fb1ec033b010
INFO: found LLVMFuzzerCustomMutator (0x557045189420). Disabling -len_control by default.
INFO: libFuzzer ignores flags that start with '--'
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1374452351
INFO: Loaded 1 modules   (165211 inline 8-bit counters): 165211 [0x557045942f48, 0x55704596b4a3), 
INFO: Loaded 1 PC tables (165211 PCs): 165211 [0x55704596b4a8,0x557045bf0a58), 
INFO: 65536 Extra Counters
./cryptofuzz: Running 1 inputs 1 time(s) each.
Running: ./crash-0001f73e5e9ceabae6cf7d3d0483fb1ec033b010
Error: The environment doesn't have randomBytes function
    at randomBytes (noble-curves.js:3240)
    at randomPrivateKey (noble-curves.js:4427)
    at k2sig (noble-curves.js:4559)
    at genUntil (noble-curves.js:3051)
    at sign (noble-curves.js:4592)
    at OpECDSA_Sign (noble-curves.js:8741)
    at <anonymous> (noble-curves.js:9173)
```

**Comment by paulmillr** [comment]
How are you dealing with this usually? Some randomBytes shim?

**Comment by guidovranken** [comment]
We should have `Math.random`. How can we make it use that? I'm trying things like adding this to harness.js:

```js
var crypto = {}
crypto.web = {};
crypto.web.getRandomValues = Math.random;
```

but to no avail.

**Comment by paulmillr** [comment]
@guidovranken removed dependency on crypto.random.

**Comment by guidovranken** [comment]
`IsBignumCalc_Mod_BLS12_381_P()` and `IsBignumCalc_Mod_BLS12_381_R()` are in `ids.js`, but don't end up in `noble-curves.js`. So I get:

```
Running: crash-e28bd7d1412d9efcb764aed4085385ab7915a860
ReferenceError: 'IsBignumCalc_Mod_BLS12_381_P' is not defined
    at <anonymous> (noble-curves.js:9262)
```

Do you know why that is?

**Comment by guidovranken** [comment]
The `HashToG2` implementation results in this error:

```
TypeError: cannot read property 'G2' of undefined
```

**Comment by paulmillr** [comment]
Crap. Too many changes during last weeks - sorry for that. 

bls.hashToCurve.G2.hashToCurve needs to be just bls.G2.hashToCurve

**Comment by paulmillr** [comment]
Fixed.

**Comment by guidovranken** [comment]
Thanks.

Do you know how to resolve this?

> `IsBignumCalc_Mod_BLS12_381_P()` and `IsBignumCalc_Mod_BLS12_381_R()` are in `ids.js`, but don't end up in `noble-curves.js`. So I get:
> 
> ```
> Running: crash-e28bd7d1412d9efcb764aed4085385ab7915a860
> ReferenceError: 'IsBignumCalc_Mod_BLS12_381_P' is not defined
>     at <anonymous> (noble-curves.js:9262)
> ```

**Comment by guidovranken** [comment]
I think this:

```javascript
    var msg = FuzzerInput['aug'] + FuzzerInput['cleartext'];                                               
```

In `OpBLS_HashToG1` and `OpBLS_HashToG2` must be changed to:

```javascript
    var msg = hexToBytes(FuzzerInput['aug'] + FuzzerInput['cleartext']);
```

Otherwise it says

```
Error: Uint8Array expected
```

**Comment by guidovranken** [comment]
Can you also please put something like this at the top of every `OpBLS_` function:

```javascript
if (!ids.IsBLS12_381(BigInt(FuzzerInput['curveType']))) return;
```

**Comment by guidovranken** [comment]
```
operation name: BLS_G2_IsEq
A V:4002409555221667393417789825735904156556882819939007885332058136124031650490837864442687629129015664037894272559787
A W:0
A X:0
A Y:0
B V:0
B W:0
B X:0
B Y:0

Module noble-curves result:

false

Module blst result:

true
```

Are you not reducing inputs?

**Comment by paulmillr** [comment]
No, inputs are not reduced mod P. Logic is done before point initialization. 

Some curves check if it's lower than P, others (ed) must behave differently because of ZIP215 and they check if it's lower than 2^256, and can reduce then

**Comment by paulmillr** [comment]
@guidovranken updated.

**Comment by paulmillr** [comment]
@guidovranken ping please

**Comment by guidovranken** [comment]
Sorry will review and merge tomorrow.

**Comment by guidovranken** [comment]
I'm reviewing this now.

This bug is still present:

> > `IsBignumCalc_Mod_BLS12_381_P()` and `IsBignumCalc_Mod_BLS12_381_R()` are in `ids.js`, but don't end up in `noble-curves.js`. So I get:
> > ```
> > Running: crash-e28bd7d1412d9efcb764aed4085385ab7915a860
> > ReferenceError: 'IsBignumCalc_Mod_BLS12_381_P' is not defined
> >     at <anonymous> (noble-curves.js:9262)
> > ```

**Comment by paulmillr** [comment]
Thanks! Now we can update curves to 1.0.0 in cryptofuzz.

**Comment by guidovranken** [comment]
Done: https://github.com/guidovranken/cryptofuzz/commit/508c3844df9d91f3bf3bde4520e1a40c9c140cc6

hash to curve calls were already ok so I didn't change those.

**Comment by guidovranken** [comment]
PS I computed a few corner cases for secp256k1 GLV endomorphism: https://github.com/guidovranken/cryptofuzz/blob/508c3844df9d91f3bf3bde4520e1a40c9c140cc6/builtin_tests_importer.cpp#L670-L719

Maybe you can add those as tests, if you haven't already.

**Comment by paulmillr** [comment]
Thanks! Do those cases pass ok, or they fail?

**Comment by guidovranken** [comment]
They passed when I checked a month ago, otherwise I would have notified you. But those edge cases are fairly rare to hit with random scalars (e.g. with fuzzing) so it makes sense to target them with tests IMO.

**Pull request merged**
